[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
privacy_subscriptions = "8GVcKi58PTZYDjaBLaDnaaxDewrWwfaSQCST5v2tFnk2"

[programs.localnet]
privacy_subscriptions = "B2WX7o3djQSAus1QdHYuezL95qUox6C1zmRS6JdDL7Ye"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=8725da20-c68a-48f9-bac4-bed8f6e9fa0a"
wallet = "~/.config/solana/id.json"

[scripts]
initialize = "yarn run ts-node scripts/initialize.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
